name: Synchronize ASC API

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: write

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  diff_spec:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./check_for_updates.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

